# This is a basic workflow to help you get started with Actions

name: Maven Package

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v2

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Create Key File
        run: echo "$GPG_PRIVATE_KEY" > private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        
      - name: Import GPG Key
        run: gpg --import --batch private.key
        
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
      - name: Build and Publish to Maven Central
        run: |
          mkdir -p ~/.m2
          cp -p settings.xml ~/.m2/settings.xml
          mvn deploy -Dgpg.passphrase="$GPG_PASSPHRASE"
